import { describe, expect, it } from "vitest";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const shpWrite = require("shp-write") as {
  zip(
    fc: GeoJSON.FeatureCollection,
    opts: {
      types: { point: string; polygon: string; line: string };
      outputType?: string;
    },
  ): Buffer;
};
import { decodeShapefileZip } from "@/lib/ingest/decode-shapefile";

const writeOpts = {
  types: { point: "points", polygon: "polygons", line: "lines" },
};

describe("decodeShapefileZip", () => {
  it("decodes a point shapefile generated by shp-write", async () => {
    const fc: GeoJSON.FeatureCollection = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: { type: "Point", coordinates: [-121.06, 39.22] },
          properties: { name: "A", count: 1 },
        },
        {
          type: "Feature",
          geometry: { type: "Point", coordinates: [-121.05, 39.23] },
          properties: { name: "B", count: 2 },
        },
      ],
    };
    const zipBuf = shpWrite.zip(fc, writeOpts);
    const decoded = await decodeShapefileZip(new Uint8Array(zipBuf));

    expect(decoded.featureCollection.features).toHaveLength(2);
    expect(decoded.componentsFound).toEqual(
      expect.arrayContaining(["shp", "dbf"]),
    );

    const first = decoded.featureCollection.features[0];
    expect(first.geometry?.type).toBe("Point");
    const coords = (first.geometry as GeoJSON.Point).coordinates;
    expect(coords[0]).toBeCloseTo(-121.06, 3);
    expect(coords[1]).toBeCloseTo(39.22, 3);
    expect((first.properties as { name: string }).name).toBe("A");
  });

  it("decodes polygons with attribute columns intact", async () => {
    const fc: GeoJSON.FeatureCollection = {
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          geometry: {
            type: "Polygon",
            coordinates: [
              [
                [-121.07, 39.21],
                [-121.06, 39.21],
                [-121.06, 39.22],
                [-121.07, 39.22],
                [-121.07, 39.21],
              ],
            ],
          },
          properties: { kind: "residential", area: 1200 },
        },
      ],
    };
    const zipBuf = shpWrite.zip(fc, writeOpts);
    const decoded = await decodeShapefileZip(new Uint8Array(zipBuf));

    expect(decoded.featureCollection.features).toHaveLength(1);
    const f = decoded.featureCollection.features[0];
    expect(f.geometry?.type).toBe("Polygon");
    expect((f.properties as { kind: string }).kind).toBe("residential");
  });

  it("rejects a zip that contains no .shp file", async () => {
    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();
    zip.file("readme.txt", "no shapefile here");
    const bytes = new Uint8Array(await zip.generateAsync({ type: "uint8array" }));
    await expect(decodeShapefileZip(bytes)).rejects.toThrow(/No \.shp/);
  });

  it("rejects a zip where the .dbf sibling is missing", async () => {
    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();
    zip.file("layer.shp", new Uint8Array(10));
    const bytes = new Uint8Array(await zip.generateAsync({ type: "uint8array" }));
    await expect(decodeShapefileZip(bytes)).rejects.toThrow(/\.dbf/);
  });
});
